openapi: "3.1.1"
info:
  title: Turing Pi 2 BMC API
  description: API for Turing Pi 2 BMC
  version: "1.1"
servers:
  - url: https://turingpi.local/
    description: Turing Pi 2 BMC API
paths:
  /api/bmc/authenticate:
    post:
      summary: Authenticate and get bearer token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Invalid credentials
  /api/bmc:
    get:
      security:
        - basicAuth: []
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    response:
                      type: object
        "401":
          description: Authentication required
        "400":
          description: Bad request
      parameters:
        - name: opt
          in: query
          required: true
          description: Operation to perform
          schema:
            type: string
            enum:
              - get
              - set
              - power
        - name: type
          in: query
          required: true
          description: Type of operation
          schema:
            type: string
            enum:
              - usb_boot
              - clear_usb_boot
              - network
              - nodeinfo
              - node_to_msd
              - other
              - power
              - reboot
              - reload
              - sdcard
              - uart
              - usb
              - info
              - about
              - flash
        - in: query
          name: node
          schema:
            type: integer
          required: false
          description: Node number (if applicable)
        - in: query
          name: mode
          schema:
            type: integer
          required: false
          description: USB mode (if applicable)
        - in: query
          name: cmd
          schema:
            type: string
          required: false
          description: UART command (if applicable)
        - in: query
          name: encoding
          schema:
            type: string
            enum:
              - utf8
              - utf16
              - utf16le
              - utf16be
              - utf32
              - utf32le
              - utf32be
          required: false
          description: UART encoding (if applicable)
        - in: query
          name: length
          schema:
            type: integer
          required: false
          description: Image length in bytes (for flash/firmware)
        - in: query
          name: local
          schema:
            type: boolean
          required: false
          description: If present, image file is read from local filesystem (for flash/firmware)
        - in: query
          name: file
          schema:
            type: string
          required: false
          description: Local file path (for flash/firmware)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic
